[[redirects]]
from = "/ads.txt"
to = "/ads.txt"
status = 200
force = true

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200
force = true

# SPA-Fallback ganz zuletzt
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]  # für /ads.txt
for = "/ads.txt"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]  # für /robots.txt
for = "/robots.txt"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
